from __future__ import annotations

from pathlib import Path


def preprocess_generated_data(raw_dir: str | Path, processed_dir: str | Path) -> Path:
    output = Path(processed_dir)
    output.mkdir(parents=True, exist_ok=True)
    marker = output / "GENERATED_SIMULATOR_DATA.txt"
    marker.write_text(
        "No external dataset is required. Samples are generated by the simulator.\n",
        encoding="utf-8",
    )
    return marker

